# -*- coding: utf-8 -*-
"""RegEx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNJYRgzaXZzz4efJhnXZ-6nBjNToD1dg
"""

#get txt file
import re
e_list=[]
try:
    file = open("dummy.txt")
    for line in file:
        line = line.strip()
        #for email
        emails = re.findall("[0-9a-zA-z]+@[0-9a-zA-z]+\.[0-9a-zA-z]+", line)
        if(len(emails) > 0):
            print(emails)
        e_list.append(emails)
 
except FileNotFoundError as e:
    print(e)

#file writing 
with open('emails.txt', 'w') as fp:
  for n in e_list:
        fp.write("%s\n" % n)

import re
no_list=[]

try:
    file = open("dummy.txt")
    for line in file:
        line = line.strip()
        #for phone number
        no =re.findall("[\+]{1}[8]{2}[0-9]{11}", line)
        print(no)
        no_list.append(no)
          
 
except FileNotFoundError as e:
    print(e)

#file writing 
with open('numbers.txt', 'w') as fp:
  for n in no_list:
        fp.write("%s\n" % n)



