# -*- coding: utf-8 -*-
"""RegEx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNJYRgzaXZzz4efJhnXZ-6nBjNToD1dg
"""

#get txt file
import re
e_list=[]
no_list=[]
try:
    file = open("dummy.txt")
    for line in file:
        line = line.strip()
        #for email
        emails = re.findall("[0-9a-zA-z]+@gmail.com+", line)
        e_list.append(emails)
        no =re.findall("[\+]{1}[8]{2}[0-9]{11}", line)
        print(no)
        no_list.append(no)
          
 
except FileNotFoundError as e:
    print(e)

#file writing 
with open('gmail_id.txt', 'w') as fp:
  for n in e_list:
        fp.write("%s\n" % n)

#file writing 
with open('bd_mobile.txt', 'w') as fp:
  for n in no_list:
        fp.write("%s\n" % n)




